### PR TITLE
sys-1 create tslint.json file to synchronize across all repos

### PR DESCRIPTION
**Pull request by ExtraGravity**
We'll use this repo to host a common tslint file, the other repos will pull from this one. I don't really know what's good in a tslint file, so I'll just let you guys pick.

### CODE REVIEW

**Comment by ExtraGravity** [comment]
use `wget https://raw.githubusercontent.com/agriculture-capstone/systems/master/tslint/tslint.json` to update the `tslint.json` file in other repos. @Right2Drive noooo problem, I gotchu ;) 

I'll wait till this is merged to get it working on other repos, otherwise the link above won't work.

**Comment by Parasrah** [comment]
Just realized the tslint has to have slightly different rules depending on the project. For example, the trader is going to need to extend the `react` linting rules

We might be better off just maintaining different linting rules, I doubt they will change very much after we initialize them

**Comment by Parasrah** [comment]
@enochtsang 
It's going to be vital to get at least some linting into the trader app ASAP. Would help steer the others with their various trader tasks. I would recommend taking the `tslint` in the `agriculture-core` repo, extending the [react tslint](https://www.npmjs.com/package/tslint-react) package, and setting up some npm scripts that they can run. Because it's not using `webpack`, it will have to use the cli tool that `tslint` provides instead of using `tslint-loader` like the others. If you need an example you can look at [this](https://github.com/Right2Drive/ease/blob/master/package.json). Extending should be easy, same way the `airbnb` rules are extended

**Comment by beaesguerra** [comment]
How will we be setting up the other repos to pull from this? Just curious about how this would work! 

Other than that, I don't really have any preferences for linting rules so maybe following a guide for the specific projects (ie. vue & react native) would be best (like Brad said)

**Comment by ExtraGravity** [comment]
So the plan would be that on every build step, we'd call a `wget` to grab the latest tslint from this repo. If for some reason it's down, it will report an error message but use the old `tslint.json`. This link https://raw.githubusercontent.com/agriculture-capstone/systems/master/tslint/tslint.json if this was merged should always work.

This is sad to do cause I really don't know what good linting rules are for TS  :( 

EDIT: Having a simple build system so we generate our `tslint.json` files is pretty easy to do as well if we need slightly different linting rules for different projects.

**Comment by ExtraGravity** [comment]
Actually I'll side with @Right2Drive for this one, if we're gonna have a diff tslint for every project we'll just manage each one individually. The overhead for a build system for our tslint.json files isn't worth it.

**Pull request closed without merging**
